### ISSUE TITLE
Feature Request: Pattern Constraint

### ISSUE THREAD

**Issue by lmt-swallow** [flatt-security/shisho#20]
## Problem

Current SHISHO pattern language can't describe the pattern like the following for the sake of autofix.

- (P)  "there's no `:[X] + 1` where `X` does not include the call of `len()` function" 

More generally, the language cant describe the following:

- negation
- deep expression #8 

## Possible Feature / Solution

Now I'm thinking about the best way to describe them.  A possible solution is introducing *pattern constraint* concepts for rules. Here's an intuitive example with the policy describing (P), with help of a pattern constraint, without a limit on autofix features:

```yaml
rules:
  - id: aaa
    language: go
    message: test
    pattern: |
      :[X] + 1
    constraints:
      - target: X
        should: not-match
        pattern:
          len(:[...])
```
