### ISSUE TITLE
Many-to-Many Relations between Pattern and Rewrite Pattern in Rule

### ISSUE THREAD

**Issue by lmt-swallow** [flatt-security/shisho#48]
# Problem

Now a rule includes only one pattern and one rewrite pattern, though it's natural that multiple patterns could be transformed into a rewrite pattern, and vice versa.

# Possible Solutions

Suppose we'd like to transform *both* of `f(:[X], :[Y])` and `g(:[X], :[Y])` into *either* of `a(:[X], :[Y])` or `b(:[X], :[Y])`. We need something like:

```yaml
version: "1"
rules:
  - id: demo
    language: go
    message: ""
    patterns: 
      - "f(:[X], :[Y])"
      - "g(:[X], :[Y])"
    rewrite-options: 
      - "a(:[X], :[Y])"
      - "b(:[X], :[Y])"
```

# Additional Notes

N/A
